/**
 * build_blog_data.js
 * Reads every .md file in /blogs, parses them into the structured format
 * expected by BlogListPage / BlogPostPage, and writes src/data/blogPosts.js
 */
const fs = require('fs');
const path = require('path');

const BLOGS_DIR = path.join(__dirname, 'blogs');
const OUTPUT = path.join(__dirname, 'src', 'data', 'blogPosts.js');

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function parseMd(content) {
  // Split by lines
  const lines = content.split(/\r?\n/);

  let title = '';
  let sections = [];
  let currentHeading = '';
  let currentBody = [];

  for (const line of lines) {
    // Stop at the social media snippets divider
    if (line.trim() === '---') break;

    // H1 = title
    if (line.startsWith('# ') && !title) {
      title = line.replace(/^#\s+/, '').trim();
      continue;
    }

    // H2 = section heading
    if (line.startsWith('## ')) {
      // Save previous section
      if (currentHeading) {
        sections.push({
          heading: currentHeading,
          body: currentBody.join(' ').replace(/\s+/g, ' ').trim()
        });
      }
      currentHeading = line.replace(/^##\s+/, '').trim();
      currentBody = [];
      continue;
    }

    // H3 = sub-heading, treat as bold text in body
    if (line.startsWith('### ')) {
      const subH = line.replace(/^###\s+/, '').trim();
      currentBody.push(`\n${subH}: `);
      continue;
    }

    // Skip empty lines or add content
    const trimmed = line.trim();
    if (trimmed && currentHeading) {
      // Clean markdown formatting for plain text display
      let clean = trimmed
        .replace(/\*\*([^*]+)\*\*/g, '$1')  // bold
        .replace(/\*([^*]+)\*/g, '$1')       // italic
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')  // links -> text only
        .replace(/^[-*]\s+/, '• ')            // list items
        ;
      currentBody.push(clean);
    } else if (trimmed && !currentHeading && title) {
      // Intro paragraph before first H2 — create an intro section
      if (!sections.length || sections[0].heading !== 'Introduction') {
        sections.unshift({ heading: 'Introduction', body: '' });
      }
      let clean = trimmed
        .replace(/\*\*([^*]+)\*\*/g, '$1')
        .replace(/\*([^*]+)\*/g, '$1')
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
        .replace(/^[-*]\s+/, '• ');
      sections[0].body += (sections[0].body ? ' ' : '') + clean;
    }
  }

  // Push last section
  if (currentHeading) {
    sections.push({
      heading: currentHeading,
      body: currentBody.join(' ').replace(/\s+/g, ' ').trim()
    });
  }

  return { title, sections };
}

// ── Main ──
const files = fs.readdirSync(BLOGS_DIR)
  .filter(f => f.endsWith('.md'))
  .sort();

console.log(`Found ${files.length} blog markdown files.`);

const posts = [];
const baseDate = new Date('2025-04-01');

for (let i = 0; i < files.length; i++) {
  const file = files[i];
  const content = fs.readFileSync(path.join(BLOGS_DIR, file), 'utf-8');
  const { title, sections } = parseMd(content);

  if (!title) {
    console.warn(`  ⚠ Skipping ${file}: no title found.`);
    continue;
  }

  const slug = slugify(title);
  // Stagger dates one day apart
  const date = new Date(baseDate);
  date.setDate(date.getDate() + i);
  const dateStr = date.toISOString().slice(0, 10);

  // Build excerpt from first section body (first ~160 chars)
  const firstBody = sections[0]?.body || '';
  const excerpt = firstBody.length > 160
    ? firstBody.slice(0, 157) + '...'
    : firstBody;

  posts.push({ slug, title, date: dateStr, excerpt, description: excerpt, sections });
  console.log(`  ✅ ${String(i + 1).padStart(3, '0')}. ${title.slice(0, 60)}`);
}

// Write output
const output = `// Auto-generated by build_blog_data.js — DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}
// Total posts: ${posts.length}

export const blogPosts = ${JSON.stringify(posts, null, 2)};
`;

fs.writeFileSync(OUTPUT, output, 'utf-8');
console.log(`\n✅ Written ${posts.length} blog posts to ${OUTPUT}`);
